### ISSUE TITLE
simtk.openmm.OpenMMException: Particle coordinate is nan

### ISSUE THREAD

**Issue by aminsagar** [ljmartin/openmm_gamd#1]
Hi. I found this repository while looking for an implementation of GAMD in openmm. Thanks for writing this and making it accessible. 
I tried it using the pdb included in the repository and it works perfectly.
However, when I am trying to use it on my system, I get an error i.e.

simtk.openmm.OpenMMException: Particle coordinate is nan

I tried reducing the timestep to 1 fs but it doesn't help.
If I keep everything exactly the same and just change the integrator to one of the default integrators, the error disappears.
The only changes I have made in the script are in the system preparation part as I start from gromacs gro+top files. 

```
def setup_system(filename):
  """Creates a 'system' object given a pdb filename"""
  gromacs.GROMACS_TOPDIR = "/run/media/amin-ub/DATA/Simulations/"
  pdb = load_file(filename)
  top = load_file('topol.top')
  top.box = pdb.box[:]
  system = top.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
  system.addForce(MonteCarloBarostat(1*bar, 310*kelvin))
  set_dihedral_force_group(system)
  print('Created system')
  return system, pdb

def set_dihedral_force_group(system, g=2):
  """Sets the dihedral forcegroup to a number other than 0,
  which will be used by serial tempering"""
  print('Scanning forces:')
  for f in system.getForces():
    if isinstance(f, PeriodicTorsionForce):
      print('Found the torsions - setting group to 2')
      f.setForceGroup(2)
    print(f.getForceGroup(), f.__class__)

def setup_simulation(system, pdb, integrator):
  """Creates a simulation object"""
  #platform = Platform.getPlatformByName('CPU')
  platform = Platform.getPlatformByName('CUDA')
  prop = dict(CudaPrecision='mixed')
  top = load_file('topol.top')
  top.box = pdb.box[:]
  simulation = Simulation(top.topology, system, integrator)
  simulation.context.setPositions(pdb.positions)
  simulation.minimizeEnergy()
  print(simulation.context.getState(getEnergy=True).getPotentialEnergy())
  simulation.context.setVelocitiesToTemperature(310*kelvin)
  print('Created simulation')
  return simulation
```

Interestingly, I changed sigma0 to a very small value (0.0001) but the error persists.

I would be really grateful if you can give me some pointers on how to address this problem.

Thanks.
Amin.

**Comment by ljmartin** [comment]
Hey Amin,
Hope you enjoyed looking through the code, thanks for reaching out. 
The PDB included here is obviously a very simple system so its reasonably robust - this is nice for validation of the implementation, although I haven't actually done that yet :) 

Since you showed that a normal integrator works fine, it's likely there is an error in my code somewhere that gets exposed when using a larger system. I'm afraid I can't recommend using this code at all for that. Please consider this repo as for fun only - it probably requires a few weeks or months of validation work to have any confidence of working on a real use-case. 
-lew

**Comment by aminsagar** [comment]
Thanks Lew. It's excellent that you have made this code public. I have used GAMD on many projects and have got nice results. The problem is that many of the newer force fields, especially for IDPs, are available only in gromacs format so it's not straight forward to convert everything to NAMD and I don't have AMBER. Your code provides a great way to use GAMD with these force fields. I will try to make it work on larger systems. Thanks again.

**Comment by ljmartin** [comment]
Yea I'd love to use GaMD with openmm too. I do know that yinglong Miao's group have been working on their own 'official' implementation, but it isn't finished. Looks like the repo is public, but note they are in the 'untested' stage too ;) 
https://github.com/MiaoLab20/GaMD-OpenMM
